### ISSUE TITLE
can not install by composer

### ISSUE THREAD

**Issue by mohamad68** [buchin/bing#1]
hi.
composer send back this error : 

> Could not find package buchin/bing at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

and, you did not mention where we should set my APIkey

**Comment by buchin** [comment]
Hi,
try: 

`composer require buchin/bing dev-master`

And FYI, this bing scraper does not require any API key :)

**Comment by mohamad68** [comment]
not require API Key!!! it doesn't have licence problem or any limitation ?

**Comment by mohamad68** [comment]
thank you for replay .
`composer require buchin/bing dev-master`

send back this error :
                                                                                                                                                             
>     - Installation request for buchin/bing dev-master -> satisfiable by buchin/bing[dev-master].                                                                        
>     - buchin/bing dev-master requires symfony/dom-crawler ^3.2 -> satisfiable by symfony/dom-crawler[3.2.x-dev, 3.3.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2,
>  v3.2.1, v3.2.2, v3.2.3, v3.2.4] but these conflict with your requirements or minimum-stability

.

**Comment by buchin** [comment]
@mohamad68 no, it's unlimited usage

It seems you need to lower your composer's minimum stability :)

**Comment by mohamad68** [comment]
how can I lower my composer's minimum stability?

**Comment by buchin** [comment]
Try to add this line before require: line in composer.json:
```
"minimum-stability": "dev",
"prefer-stable": true,
```
